/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.Presentation;

import com.mycompany.Services.ServiceLocator;
import javax.swing.JInternalFrame;

/**
 *
 * @author kosmo
 */
public class FrmAdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmAdminMenu
     */
    public FrmAdminMenu() {
        initComponents();
    }

    /**
     * Abre una ventana interna ({@link javax.swing.JInternalFrame}) dentro del
     * {@link javax.swing.JDesktopPane}.
     * <p>
     * Este método se encarga de ocultar todas las demás ventanas internas
     * abiertas y mostrar únicamente la que se pasa como parámetro. Si la
     * ventana aún no ha sido agregada al {@code desktopPane}, se añade
     * automáticamente.
     * </p>
     *
     * <p>
     * <strong>Flujo general:</strong></p>
     * <ol>
     * <li>Oculta todos los {@code JInternalFrame} actualmente visibles.</li>
     * <li>Agrega el nuevo {@code frame} al {@code desktopPane} si no está
     * presente.</li>
     * <li>Lo hace visible, lo trae al frente y le da el foco.</li>
     * </ol>
     *
     * @param frame instancia de {@link javax.swing.JInternalFrame} que se desea
     * mostrar.
     */
    private void openInternalFrame(javax.swing.JInternalFrame frame) {
        // Oculta las ventanas internas abiertas.
        for (JInternalFrame f : desktopPane.getAllFrames()) {
            f.setVisible(false);
        }
        // Si la ventana no está en el escritorio, agregarla
        if (frame.getParent() != desktopPane) {
            desktopPane.add(frame);
        }
        //Mostrar la ventana y traerla al frente
        frame.setVisible(true);
        frame.toFront();

        try {
            frame.setSelected(true); //Intenta darle foco (recibir las acciones del usuario).
        } catch (java.beans.PropertyVetoException e) {
            System.err.println("Error selecting frame: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        btnRemoveDoctor = new javax.swing.JButton();
        btnAddNewDoctor = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        btnAddNewSpecialty = new javax.swing.JButton();
        upperPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        desktopPane.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        btnRemoveDoctor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnRemoveDoctor.setText("Remove Doctor");
        btnRemoveDoctor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 225), 3, true));
        btnRemoveDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveDoctorActionPerformed(evt);
            }
        });
        jPanel2.add(btnRemoveDoctor);
        btnRemoveDoctor.setBounds(310, 160, 173, 90);

        btnAddNewDoctor.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAddNewDoctor.setText("Add New Doctor");
        btnAddNewDoctor.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 225), 3, true));
        btnAddNewDoctor.setPreferredSize(new java.awt.Dimension(130, 30));
        btnAddNewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDoctorActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddNewDoctor);
        btnAddNewDoctor.setBounds(80, 160, 170, 90);

        btnLogout.setBackground(new java.awt.Color(102, 102, 255));
        btnLogout.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("Cerrar Sesión");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel2.add(btnLogout);
        btnLogout.setBounds(570, 360, 140, 36);

        lblWelcome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblWelcome.setText("Welcome, Administrator");
        jPanel2.add(lblWelcome);
        lblWelcome.setBounds(259, 23, 290, 30);

        btnAddNewSpecialty.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnAddNewSpecialty.setText("Add New Specialty");
        btnAddNewSpecialty.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 3));
        btnAddNewSpecialty.setPreferredSize(new java.awt.Dimension(130, 30));
        btnAddNewSpecialty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewSpecialtyActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddNewSpecialty);
        btnAddNewSpecialty.setBounds(540, 160, 170, 90);

        desktopPane.add(jPanel2);
        jPanel2.setBounds(0, 40, 800, 500);

        upperPanel.setBackground(new java.awt.Color(102, 102, 255));
        upperPanel.setPreferredSize(new java.awt.Dimension(800, 50));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        desktopPane.add(upperPanel);
        upperPanel.setBounds(0, 0, 800, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        dispose();
        new FrmLogin(ServiceLocator.getInstance().getAuthenticationService()).setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnAddNewSpecialtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewSpecialtyActionPerformed

    }//GEN-LAST:event_btnAddNewSpecialtyActionPerformed

    private void btnAddNewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDoctorActionPerformed
        FrmAddNewDoctor frm = new FrmAddNewDoctor(ServiceLocator.getInstance().getDoctorService(),
                ServiceLocator.getInstance().getSpecialtyService());
        openInternalFrame(frm);
    }//GEN-LAST:event_btnAddNewDoctorActionPerformed

    private void btnRemoveDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveDoctorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewDoctor;
    private javax.swing.JButton btnAddNewSpecialty;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnRemoveDoctor;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

}
