/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.Presentation;

import com.mycompany.Models.Doctor;
import com.mycompany.Models.Specialty;
import com.mycompany.Services.DoctorService;
import com.mycompany.Services.ServiceLocator;
import com.mycompany.Services.SpecialtyService;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author kosmo
 */
public class FrmAddNewDoctor extends javax.swing.JInternalFrame {

    private final DoctorService doctorService;
    private final SpecialtyService specialtyService;
    private List<Specialty> specialtiesList;

    /**
     * Creates new form FrmAddNewDoctor
     *
     * @param doctorService
     * @param specialtyService
     */
    public FrmAddNewDoctor(DoctorService doctorService, SpecialtyService specialtyService) {
        initComponents();
        this.doctorService = doctorService;
        this.specialtyService = specialtyService;
        loadAllSpecialties();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        upperPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        txtFullNameField = new javax.swing.JTextField();
        txtPhoneNumberField = new javax.swing.JTextField();
        txtUsernameField = new javax.swing.JTextField();
        txtDocumentNumberField = new javax.swing.JTextField();
        txtPasswordField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnRegisterDoctor = new javax.swing.JButton();
        btnCancelRegistration = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cmbSpecialties = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        upperPanel.setBackground(new java.awt.Color(102, 102, 255));
        upperPanel.setPreferredSize(new java.awt.Dimension(800, 50));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(upperPanel);
        upperPanel.setBounds(0, 0, 800, 50);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(800, 450));

        txtFullNameField.setBackground(new java.awt.Color(255, 255, 255));
        txtFullNameField.setForeground(new java.awt.Color(0, 0, 0));
        txtFullNameField.setPreferredSize(new java.awt.Dimension(300, 50));

        txtPhoneNumberField.setBackground(new java.awt.Color(255, 255, 255));
        txtPhoneNumberField.setForeground(new java.awt.Color(0, 0, 0));
        txtPhoneNumberField.setPreferredSize(new java.awt.Dimension(300, 50));

        txtUsernameField.setBackground(new java.awt.Color(255, 255, 255));
        txtUsernameField.setForeground(new java.awt.Color(0, 0, 0));
        txtUsernameField.setPreferredSize(new java.awt.Dimension(300, 50));

        txtDocumentNumberField.setBackground(new java.awt.Color(255, 255, 255));
        txtDocumentNumberField.setForeground(new java.awt.Color(0, 0, 0));
        txtDocumentNumberField.setPreferredSize(new java.awt.Dimension(300, 50));

        txtPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        txtPasswordField.setForeground(new java.awt.Color(0, 0, 0));
        txtPasswordField.setPreferredSize(new java.awt.Dimension(300, 50));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Full Name");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Document Number");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cellphone Number");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Specialty");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Username");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Password");

        btnRegisterDoctor.setText("Register");
        btnRegisterDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterDoctorActionPerformed(evt);
            }
        });

        btnCancelRegistration.setText("Cancel");
        btnCancelRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegistrationActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Doctor Registration");

        cmbSpecialties.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtFullNameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhoneNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(60, 60, 60)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(txtDocumentNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPasswordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnRegisterDoctor)
                                .addGap(38, 38, 38)
                                .addComponent(btnCancelRegistration))
                            .addComponent(cmbSpecialties, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(jLabel7)))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDocumentNumberField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPhoneNumberField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbSpecialties, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterDoctor)
                    .addComponent(btnCancelRegistration))
                .addGap(56, 56, 56))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 50, 800, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterDoctorActionPerformed
        //Obtener los datos de los campos de texto
        var realName = txtFullNameField.getText();
        var username = txtUsernameField.getText();
        var password = txtPasswordField.getText();
        var documentNumber = txtDocumentNumberField.getText();
        var phoneNumber = txtPhoneNumberField.getText();
        //Obtener la especialidad seleccionada
        int selectedIndex = cmbSpecialties.getSelectedIndex();

        Specialty specialty = null;
        if (selectedIndex >= 0 && selectedIndex < specialtiesList.size()) {
            specialty = specialtiesList.get(selectedIndex);
        }

        //Una vez obtenido, se llama al servicio de médicos:
        if (this.doctorService.registerDoctor(new Doctor(username, phoneNumber,
                password, realName, documentNumber, specialty))) {
            JOptionPane.showMessageDialog(this, "Registration Success!");
            //Si se registra exitosamente, se le regresa al menú de admin
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this, "Registration Failed!",
                    "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisterDoctorActionPerformed
    private void loadAllSpecialties() {
        //Limpiar el ComboBox
        cmbSpecialties.removeAllItems();

        //Obtener todas las especialidades
        this.specialtiesList = specialtyService.listAllSpecialties();

        if (specialtiesList == null || specialtiesList.isEmpty()) {
            cmbSpecialties.addItem("No specialties available!");
        } else {
            //Agregar cada especialidad al ComboBox
            for (Specialty specialty : specialtiesList) {
                String displayText = "***" + specialty.getSpecialtyName() + "***";
                cmbSpecialties.addItem(displayText);
            }
        }
    }
    private void btnCancelRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegistrationActionPerformed
        // Regresa al login
        FrmLogin login = new FrmLogin(ServiceLocator.getInstance().getAuthenticationService());
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelRegistrationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelRegistration;
    private javax.swing.JButton btnRegisterDoctor;
    private javax.swing.JComboBox<String> cmbSpecialties;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtDocumentNumberField;
    private javax.swing.JTextField txtFullNameField;
    private javax.swing.JTextField txtPasswordField;
    private javax.swing.JTextField txtPhoneNumberField;
    private javax.swing.JTextField txtUsernameField;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
