/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.Presentation;

import com.mycompany.Models.User;
import com.mycompany.Services.DoctorService;
import com.mycompany.Services.PatientService;
import com.mycompany.Services.ServiceLocator;
import java.awt.HeadlessException;

/**
 *
 * @author camil
 */
public class FrmInformation extends javax.swing.JInternalFrame {

    private final User user;
    private final DoctorService doctorService;
    private final PatientService patientService;

    /**
     * Creates new form FrmInformation
     *
     * @param user
     */
    public FrmInformation(User user) {
        initComponents();
        this.user = user;

        // Obtener los servicios del ServiceLocator
        this.doctorService = ServiceLocator.getInstance().getDoctorService();
        this.patientService = ServiceLocator.getInstance().getPatientService();

        // Configurar la UI
        setSize(800, 500);
        loadUserInformation();
        txtDocument.setEnabled(false); // documento no editable
    }

    private void loadUserInformation() {
        txtFullName2.setText(user.getFullName());
        txtDocument.setText(user.getDocumentNumber());
        txtPhoneNumber.setText(user.getPhoneNumber());
        txtUserName.setText(user.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbtTitle = new javax.swing.JLabel();
        upperPanel = new javax.swing.JPanel();
        txtDocument = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtFullName2 = new javax.swing.JTextField();
        txtPhoneNumber = new javax.swing.JTextField();
        lblFullName = new javax.swing.JLabel();
        lblPhoneNumber = new javax.swing.JLabel();
        lblDocument1 = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        btnRegisterConsultation = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lbtTitle.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbtTitle.setText("Information");

        upperPanel.setBackground(new java.awt.Color(102, 102, 255));
        upperPanel.setPreferredSize(new java.awt.Dimension(800, 50));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 38, Short.MAX_VALUE)
        );

        txtDocument.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtDocument.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtDocument.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentActionPerformed(evt);
            }
        });

        txtUserName.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtUserName.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtUserName.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });

        txtFullName2.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtFullName2.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtFullName2.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtFullName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFullName2ActionPerformed(evt);
            }
        });

        txtPhoneNumber.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        txtPhoneNumber.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtPhoneNumber.setSelectionColor(new java.awt.Color(0, 0, 0));
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });

        lblFullName.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFullName.setText("Full Name:");

        lblPhoneNumber.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblPhoneNumber.setText("Phone:");

        lblDocument1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblDocument1.setText("Document:");

        lblUsername.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblUsername.setText("Username:");

        btnRegisterConsultation.setBackground(new java.awt.Color(102, 102, 225));
        btnRegisterConsultation.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnRegisterConsultation.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterConsultation.setText("Save Changes");
        btnRegisterConsultation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterConsultationActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(329, 329, 329)
                .addComponent(lbtTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRegisterConsultation)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFullName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDocument1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtUserName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFullName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDocument, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(btnCancel)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(upperPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbtTitle)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFullName2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFullName))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDocument, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDocument1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoneNumber))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsername))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisterConsultation, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentActionPerformed

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void txtFullName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFullName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFullName2ActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRegisterConsultationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterConsultationActionPerformed
        try {
            String fullName = txtFullName2.getText().trim();
            String phone = txtPhoneNumber.getText().trim();
            String username = txtUserName.getText().trim();

            if (fullName.isEmpty() || phone.isEmpty() || username.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(this, "Please fill in all fields before saving.");
                return;
            }

            // Actualizamos los valores locales
            user.setFullName(fullName);
            user.setPhoneNumber(phone);
            user.setUsername(username);

            // Llamar al servicio correspondiente
            boolean success;
            if (user instanceof com.mycompany.Models.Doctor doctor) {
                success = doctorService.updateDoctor(doctor);
            } else if (user instanceof com.mycompany.Models.Patient patient) {
                success = patientService.updatePatient(patient);
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Unknown user type.");
                return;
            }

            if (success) {
                javax.swing.JOptionPane.showMessageDialog(this, "Information updated successfully!");
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Failed to update information.");
            }

        } catch (HeadlessException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error updating information: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnRegisterConsultationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRegisterConsultation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDocument1;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lbtTitle;
    private javax.swing.JTextField txtDocument;
    private javax.swing.JTextField txtFullName2;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
