/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.Presentation;

import com.mycompany.Models.Patient;
import com.mycompany.Models.User;
import com.mycompany.Services.ServiceLocator;
import java.awt.FontMetrics;
import javax.swing.JOptionPane;

/**
 *
 * @author mateo
 */
public class FrmPatientMenu extends javax.swing.JFrame {

    private final Patient patient;

    /**
     * Creates new form FrmPatientMenu
     *
     * @param patient
     */
    public FrmPatientMenu(Patient patient) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.patient = patient;

        // Texto completo
        String fullName = this.patient.getFullName();
        String message = "Welcome, Patient " + fullName;

        // Mostrar todo el nombre en tooltip por si es muy largo
        jLabel1.setToolTipText(message);

        // Usar HTML con ajuste automático
        jLabel1.setText("<html><div style='text-align:center; white-space: nowrap;'>"
                + message + "</div></html>");

        // Escucha de cambios en el tamaño del label (por si cambia el ancho de la ventana)
        jLabel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent e) {
                int width = jLabel1.getWidth();
                jLabel1.setText("<html><div style='text-align:center; width:" + width + "px;'>"
                        + message + "</div></html>");
            }
        });
    }

    private void refreshWelcomeMessage() {
        if (patient != null) {
            String fullName = patient.getFullName();
            String message = "Welcome, Dr. " + fullName;

            jLabel1.setToolTipText(message);

            // Medir el ancho del texto
            FontMetrics fm = jLabel1.getFontMetrics(jLabel1.getFont());
            int textWidth = fm.stringWidth(message);
            int labelWidth = jLabel1.getWidth();
            float MIN_FONT_SIZE = 15.0f;
            // Si el texto es más ancho que el label, reducir la fuente
            if (textWidth > labelWidth && labelWidth > 0) {
                float ratio = (float) labelWidth / textWidth;
                float newSize = jLabel1.getFont().getSize() * ratio * 0.9f; // 0.9 para margen

                newSize = Math.max(newSize, MIN_FONT_SIZE); //Elige el más grande
                jLabel1.setFont(jLabel1.getFont().deriveFont(newSize));
            }

            jLabel1.setText(message);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        btnSignOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnScheduledAppointments = new javax.swing.JButton();
        btnNewAppointment = new javax.swing.JButton();
        btnAppointmentHistory = new javax.swing.JButton();
        btnEditPatientInfo = new javax.swing.JButton();
        upperPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setPreferredSize(new java.awt.Dimension(800, 500));

        btnSignOut.setBackground(new java.awt.Color(102, 102, 255));
        btnSignOut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSignOut.setForeground(new java.awt.Color(255, 255, 255));
        btnSignOut.setText("Sign out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        desktopPane.add(btnSignOut);
        btnSignOut.setBounds(650, 390, 110, 40);

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Welcome, x");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(60, 80, 570, 47);

        btnScheduledAppointments.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnScheduledAppointments.setText("Scheduled Appointments");
        btnScheduledAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnScheduledAppointmentsMouseClicked(evt);
            }
        });
        btnScheduledAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduledAppointmentsActionPerformed(evt);
            }
        });
        desktopPane.add(btnScheduledAppointments);
        btnScheduledAppointments.setBounds(60, 170, 180, 160);

        btnNewAppointment.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnNewAppointment.setText("New Appointment");
        btnNewAppointment.setMaximumSize(new java.awt.Dimension(100, 23));
        btnNewAppointment.setMinimumSize(new java.awt.Dimension(100, 23));
        btnNewAppointment.setPreferredSize(new java.awt.Dimension(100, 23));
        btnNewAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewAppointmentMouseClicked(evt);
            }
        });
        btnNewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAppointmentActionPerformed(evt);
            }
        });
        desktopPane.add(btnNewAppointment);
        btnNewAppointment.setBounds(310, 170, 180, 160);

        btnAppointmentHistory.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAppointmentHistory.setText("Appointment History");
        btnAppointmentHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAppointmentHistoryMouseClicked(evt);
            }
        });
        desktopPane.add(btnAppointmentHistory);
        btnAppointmentHistory.setBounds(560, 170, 180, 160);

        btnEditPatientInfo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnEditPatientInfo.setText("Edit Profile");
        btnEditPatientInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditPatientInfoMouseClicked(evt);
            }
        });
        desktopPane.add(btnEditPatientInfo);
        btnEditPatientInfo.setBounds(640, 90, 100, 40);

        upperPanel.setBackground(new java.awt.Color(102, 102, 255));
        upperPanel.setPreferredSize(new java.awt.Dimension(800, 50));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        desktopPane.add(upperPanel);
        upperPanel.setBounds(0, 0, 800, 50);

        menuBar.setBackground(new java.awt.Color(102, 102, 255));
        menuBar.setForeground(new java.awt.Color(102, 102, 255));
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScheduledAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduledAppointmentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnScheduledAppointmentsActionPerformed

    private void btnNewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAppointmentActionPerformed

    }//GEN-LAST:event_btnNewAppointmentActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        JOptionPane.showMessageDialog(this, "You signed out!");
        //Al cerrar sesión se regresará al login:

        FrmLogin login = new FrmLogin(ServiceLocator.getInstance().getAuthenticationService());
        login.setLocationRelativeTo(null);
        login.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnNewAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewAppointmentMouseClicked
        FrmNewAppointment newAppt = new FrmNewAppointment(ServiceLocator.getInstance().getAppointmentService(),
                ServiceLocator.getInstance().getDoctorService(),
                ServiceLocator.getInstance().getPatientService(), patient);
        this.desktopPane.add(newAppt);
        newAppt.setVisible(true);
    }//GEN-LAST:event_btnNewAppointmentMouseClicked

    private void btnScheduledAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScheduledAppointmentsMouseClicked
        FrmScheduledAppointments scheduledAppt = new FrmScheduledAppointments(ServiceLocator.getInstance().getAppointmentService(), patient);
        this.desktopPane.add(scheduledAppt);
        scheduledAppt.setVisible(true);
    }//GEN-LAST:event_btnScheduledAppointmentsMouseClicked

    private void btnAppointmentHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentHistoryMouseClicked
        FrmPatientHistory patientHistory = new FrmPatientHistory(ServiceLocator.getInstance().getAppointmentService(),
                ServiceLocator.getInstance().getConsultationService(),
                patient);
        this.desktopPane.add(patientHistory);
        patientHistory.setVisible(true);
    }//GEN-LAST:event_btnAppointmentHistoryMouseClicked

    private void btnEditPatientInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPatientInfoMouseClicked
        FrmInformation information = new FrmInformation(patient);
        desktopPane.add(information);
        information.setVisible(true);
        information.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent e) {
                refreshWelcomeMessage(); // Actualiza el nombre
            }

        });
    }//GEN-LAST:event_btnEditPatientInfoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointmentHistory;
    private javax.swing.JButton btnEditPatientInfo;
    private javax.swing.JButton btnNewAppointment;
    private javax.swing.JButton btnScheduledAppointments;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

}
