/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package com.mycompany.Presentation;

import com.mycompany.Services.ServiceLocator;
import javax.swing.JOptionPane;

/**
 *
 * @author mateo
 */
public class FrmPatientMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmPatientMenu
     */
    public FrmPatientMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        btnSignOut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnScheduledAppointments = new javax.swing.JButton();
        btnNewAppointment = new javax.swing.JButton();
        btnAppointmentHistory = new javax.swing.JButton();
        btnEditPatientInfo = new javax.swing.JButton();
        upperPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setPreferredSize(new java.awt.Dimension(800, 500));

        btnSignOut.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSignOut.setText("Sign out");
        btnSignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignOutActionPerformed(evt);
            }
        });
        desktopPane.add(btnSignOut);
        btnSignOut.setBounds(650, 390, 110, 40);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Welcome, x");
        desktopPane.add(jLabel1);
        jLabel1.setBounds(330, 70, 150, 32);

        btnScheduledAppointments.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnScheduledAppointments.setText("Scheduled Appointments");
        btnScheduledAppointments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnScheduledAppointmentsMouseClicked(evt);
            }
        });
        btnScheduledAppointments.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScheduledAppointmentsActionPerformed(evt);
            }
        });
        desktopPane.add(btnScheduledAppointments);
        btnScheduledAppointments.setBounds(60, 170, 180, 160);

        btnNewAppointment.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnNewAppointment.setText("New Appointment");
        btnNewAppointment.setMaximumSize(new java.awt.Dimension(100, 23));
        btnNewAppointment.setMinimumSize(new java.awt.Dimension(100, 23));
        btnNewAppointment.setPreferredSize(new java.awt.Dimension(100, 23));
        btnNewAppointment.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNewAppointmentMouseClicked(evt);
            }
        });
        btnNewAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAppointmentActionPerformed(evt);
            }
        });
        desktopPane.add(btnNewAppointment);
        btnNewAppointment.setBounds(310, 170, 180, 160);

        btnAppointmentHistory.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnAppointmentHistory.setText("Appointment History");
        btnAppointmentHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAppointmentHistoryMouseClicked(evt);
            }
        });
        desktopPane.add(btnAppointmentHistory);
        btnAppointmentHistory.setBounds(560, 170, 180, 160);

        btnEditPatientInfo.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        btnEditPatientInfo.setText("Edit Profile");
        btnEditPatientInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditPatientInfoMouseClicked(evt);
            }
        });
        desktopPane.add(btnEditPatientInfo);
        btnEditPatientInfo.setBounds(640, 90, 100, 40);

        upperPanel.setBackground(new java.awt.Color(102, 102, 255));
        upperPanel.setPreferredSize(new java.awt.Dimension(800, 50));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        desktopPane.add(upperPanel);
        upperPanel.setBounds(0, 0, 800, 50);

        menuBar.setBackground(new java.awt.Color(102, 102, 255));
        menuBar.setForeground(new java.awt.Color(102, 102, 255));
        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnScheduledAppointmentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScheduledAppointmentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnScheduledAppointmentsActionPerformed

    private void btnNewAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAppointmentActionPerformed
        
    }//GEN-LAST:event_btnNewAppointmentActionPerformed

    private void btnSignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignOutActionPerformed
        JOptionPane.showMessageDialog(this, "You signed out!");
        //Al cerrar sesión se regresará al login:
        /*
        FrmLogin login = new FrmLogin(ServiceLocator.getInstance().getAuthenticationService());
        login.setLocationRelativeTo(null);
            
        this.dispose();
        */
    }//GEN-LAST:event_btnSignOutActionPerformed

    private void btnNewAppointmentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNewAppointmentMouseClicked
        FrmNewAppointment newAppt = new FrmNewAppointment();
        this.desktopPane.add(newAppt);
        newAppt.setVisible(true);
    }//GEN-LAST:event_btnNewAppointmentMouseClicked

    private void btnScheduledAppointmentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnScheduledAppointmentsMouseClicked
        FrmScheduledAppointments scheduledAppt = new FrmScheduledAppointments();
        this.desktopPane.add(scheduledAppt);
        scheduledAppt.setVisible(true);
    }//GEN-LAST:event_btnScheduledAppointmentsMouseClicked

    private void btnAppointmentHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAppointmentHistoryMouseClicked
        FrmPatientHistory patientHistory = new FrmPatientHistory();
        this.desktopPane.add(patientHistory);
        patientHistory.setVisible(true);
    }//GEN-LAST:event_btnAppointmentHistoryMouseClicked

    private void btnEditPatientInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditPatientInfoMouseClicked
        FrmInformation information = new FrmInformation();
        desktopPane.add(information);
        information.setVisible(true);
    }//GEN-LAST:event_btnEditPatientInfoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPatientMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPatientMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAppointmentHistory;
    private javax.swing.JButton btnEditPatientInfo;
    private javax.swing.JButton btnNewAppointment;
    private javax.swing.JButton btnScheduledAppointments;
    private javax.swing.JButton btnSignOut;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables

}
