/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.Presentation;

import com.mycompany.Models.Appointment;
import com.mycompany.Models.AppointmentStatus;
import com.mycompany.Models.Doctor;
import com.mycompany.Services.AppointmentService;
import com.mycompany.Services.DoctorService;
import com.mycompany.Services.ServiceLocator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author kosmo
 */
public class FrmRemoveDoctorMenu extends javax.swing.JInternalFrame {

    private final DoctorService doctorService;
    private final AppointmentService appointmentService;
    private DefaultListModel<String> doctorsList;

    /**
     * Creates new form FrmRemoveDoctorMenu
     *
     * @param doctorService el servicio de médicos
     * @param appointmentService el servicio de citas
     */
    public FrmRemoveDoctorMenu(DoctorService doctorService, AppointmentService appointmentService) {
        initComponents();
        this.doctorsList = new DefaultListModel<>();//Para que la lista sea dinámica
        this.doctorService = doctorService; //Servicio de médicos
        this.appointmentService = appointmentService; // Servicio de citas
        initListDynamicModel();
        loadDoctorsList();
    }

    public DefaultListModel<String> getListModel() {
        return doctorsList;
    }

    private void initListDynamicModel() {
        if (getListModel() != null) {
            jList1.setModel(getListModel());
        }

    }

    private void loadDoctorsList() {
        //Limpia la lista
        this.doctorsList.clear();

        List<Doctor> doctors = doctorService.listAllDoctors(); //Lista médicos activos

        if (doctors == null || doctors.isEmpty()) {
            JOptionPane.showMessageDialog(this, "There are no Doctors Available.",
                    "Empty List",
                    JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        for (Doctor doctor : doctors) {
            this.doctorsList.addElement(doctor.getFullName() + " - " + doctor.getId());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        brnDelete = new javax.swing.JButton();
        lblWelcome = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        btnCancel = new javax.swing.JButton();
        upperPanel = new javax.swing.JPanel();

        desktopPane.setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        brnDelete.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        brnDelete.setText("Delete Selected Doctor");
        brnDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 225), 3, true));
        brnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnDeleteActionPerformed(evt);
            }
        });

        lblWelcome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblWelcome.setText("Remove Doctor Menu");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brnDelete)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(btnCancel))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 651, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(brnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel2);
        jPanel2.setBounds(0, 40, 800, 500);

        upperPanel.setBackground(new java.awt.Color(102, 102, 255));
        upperPanel.setPreferredSize(new java.awt.Dimension(800, 50));

        javax.swing.GroupLayout upperPanelLayout = new javax.swing.GroupLayout(upperPanel);
        upperPanel.setLayout(upperPanelLayout);
        upperPanelLayout.setHorizontalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        upperPanelLayout.setVerticalGroup(
            upperPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        desktopPane.add(upperPanel);
        upperPanel.setBounds(0, 0, 800, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void brnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnDeleteActionPerformed
        System.out.println(">>> Eliminando Doctor...");
        if (this.doctorsList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "There are no Doctors to delete!",
                    "Empty List.", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int index = jList1.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Please, select a Doctor first.");
            return;
        }
        String selected = jList1.getSelectedValue(); //obtiene el string
        String[] parts = selected.split(" - ", 2); //Separa id y nombre
        String id = parts[1]; //Guarda id

        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you wish to delete this Doctor?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            doctorService.removeDoctor(id);
            //Cancelar citas del médico desactivado
            List<Appointment> list
                    = appointmentService.
                            getAppointmentsByDoctor(id, AppointmentStatus.PROGRAMADA);

            if (!list.isEmpty()) {
                for (Appointment appointment : list) {
                    appointmentService.
                            updateAppointmentStatus(appointment.getId(),
                                    AppointmentStatus.CANCELADA);
                }
            }

            System.out.println("=== DEBUG INFO ===");
            System.out.println("Doctor desactivdo: " + selected);
            loadDoctorsList();

        }
    }//GEN-LAST:event_brnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnDelete;
    private javax.swing.JButton btnCancel;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel upperPanel;
    // End of variables declaration//GEN-END:variables
}
